### ISSUE TITLE
Catalog Methods

### ISSUE THREAD

**Issue by aroningruber** [aroningruber/scryfall_api#28]
### Description

Implement the methods used to query catalogs.

The API documentation for these methods can be found [here](https://scryfall.com/docs/api/catalogs).

### Tasks

- [x] GET /catalog/card-names
- [x] GET /catalog/artist-names
- [x] GET /catalog/word-bank
- [x] GET /catalog/creature-types
- [x] GET /catalog/planeswalker-types
- [x] GET /catalog/land-types
- [x] GET /catalog/artifact-types
- [x] GET /catalog/enchantment-types
- [x] GET /catalog/spell-types
- [x] GET /catalog/powers
- [x] GET /catalog/toughnesses
- [x] GET /catalog/loyalties
- [x] GET /catalog/watermarks
- [x] GET /catalog/keyword-abilities
- [x] GET /catalog/keyword-actions
- [x] GET /catalog/ability-words
